name: Set up postgres (linux)
description: Set up and configure a postgres database on linux for integration tests

runs:
  using: composite
  steps:

    - name: Start the postgres service
      run: sudo systemctl start postgresql.service
      shell: bash

    - name: Configure the database
      run: sudo -u postgres psql -f ./scripts/setup_test_database.sql
      shell: bash
