name: Set up postgres (linux)
description: Set up and configure a postgres database on linux for integration tests

runs:
  using: composite
  steps:

    - name: Start the postgres service
      shell: bash
      run: |
        sudo systemctl start postgresql.service
        pg_isready

    - name: Configure the database
      shell: bash
      run: sudo su - postgres psql -c 'select 1 as id'
