name: Set up postgres (linux)
description: Set up and configure a postgres database on linux for integration tests

runs:
  using: composite
  steps:

    - name: Start the postgres service
      shell: bash
      run: |
        sudo systemctl start postgresql.service
        pg_isready

    - name: Configure the database
      shell: bash
      run: |
        sudo su - postgres bash "PGUSER=postgres"
        sudo su - postgres bash "export PGUSER"
        sudo su - postgres bash "PGPORT=5432"
        sudo su - postgres bash "export PGPORT"
        sudo su - postgres bash "PGHOST=localhost"
        sudo su - postgres bash "export PGHOST"
        sudo su - postgres bash "createdb dbt"
