name: Set up postgres (linux)
description: Set up and configure a postgres database on linux for integration tests

runs:
  using: composite
  steps:

    - name: Start the postgres service
      shell: bash
      run: |
        sudo systemctl start postgresql.service
        pg_isready

    - name: Can I cd "/home/runner/work/dbt-postgres/dbt-postgres"?
      shell: bash
      run: |
        sudo -u postgres bash -c "pwd"
        sudo -u postgres bash -c "ls"
        sudo -u postgres bash -c "cd ."

    - name: Configure the database
      shell: bash
      run: sudo -u postgres psql -c "CREATE DATABASE dbt;"
