name: Set up postgres (linux)
description: Set up and configure a postgres database on linux for integration tests

runs:
  using: composite
  steps:

    - name: Start the postgres service
      shell: bash
      run: echo "woohoo"
#        sudo systemctl start postgresql.service
#        pg_isready
#        sudo chmod a+x ${{ github.action_path }}/setup_db.sh
#        sudo -u postgres bash ${{ github.action_path }}/setup_db.sh
