name: Set up postgres (linux)
description: Set up and configure postgres database on linux for integration tests

runs:
  using: composite
  steps:

    - name: Start postgres service
      run: |
        sudo systemctl start postgresql.service
        pg_isready
        ./setup_postgres_linux.sh
      shell: bash
      working-directory: ./.github/scripts
