name: Set up postgres (linux)
description: Set up and configure a postgres database on linux for integration tests

runs:
  using: composite
  steps:

    - name: Start the postgres service
      run: |
        sudo systemctl start postgresql.service
        pg_isready
      shell: bash

    - name: Configure the database
      run: |
        chmod +x setup_postgres_linux.sh
        sudo -u postgres bash setup_postgres_linux.sh
      shell: bash
      working-directory: ./.github/scripts
