name: Changelog entry check

on:
    pull_request:
        types:
        -   opened
        -   reopened
        -   labeled
        -   unlabeled
        -   synchronize

defaults:
    run:
        shell: bash

permissions:
    contents: read
    pull-requests: write

jobs:
    changelog-entry-check:
        uses: dbt-labs/dbt-adapters/.github/workflows/_changelog-entry-check.yml@main
        with:
            pull-request: ${{ github.event.pull_request.number }}
        secrets: inherit
