name: Code Quality

on:
  push:
    branches:
      - "main"
      - "*.latest"
  pull_request:
  workflow_dispatch:
    inputs:
      dbt_adapters_branch:
          description: "The branch of dbt-adapters to evaluate"
          type: string
          required: true
          default: "main"
  workflow_call:
    inputs:
      dbt_adapters_branch:
        description: "The branch of dbt-adapters to evaluate"
        type: string
        required: true
        default: "main"

permissions: read-all

# will cancel previous workflows triggered by the same event and for the same ref for PRs or same SHA otherwise
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref || github.sha }}
  cancel-in-progress: true

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Update Adapters and Core branches
        if: ${{ github.event_name == 'workflow_call' || github.event_name == 'workflow_dispatch'}}
        shell: bash
        run: |
          ./.github/scripts/update_dev_packages.sh \
            ${{ github.event.inputs.dbt_adapters_branch }} \
            "main"

      - name: Setup `hatch`
        uses: dbt-labs/dbt-adapters/.github/actions/setup-hatch@${{ inputs.dbt_adapters_branch }}

      - name: Run linters
        run: hatch run lint:all

      - name: Run typechecks
        run: hatch run typecheck:all
