# https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions
name: Empty Workflow

on:
  push:
    branches:
      - "main"
      - "*.latest"
  pull_request:

permissions: read-all

jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run script
        run: ./empty_script.sh
