name: Example Job

on:
  push:
    branches:
      - "main"
      - "*.latest"
  pull_request:

permissions: read-all

# https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions
jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Run a script
        run: ./my-script.sh

  example-job-bash-default:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
        shell: bash
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Run a script
        run: ./my-script.sh

  example-job-bash-in-step:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Run a script
        run: ./my-script.sh
        shell: bash

  example-job-bash-inline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Run a script
        run: bash ./my-script.sh
