name: Integration Tests

on:
  push:
    branches:
      - "main"
      - "*.latest"
  pull_request:
  workflow_dispatch:
    dbt_adapters_branch:
      inputs:
        description: "The branch of dbt-adapters to evaluate"
        type: string
        required: true
        default: "main"
  workflow_call:
    inputs:
      dbt_adapters_branch:
        description: "The branch of dbt-adapters to use"
        type: string
        required: true
        default: "main"
      core_branch:
        description: "The branch of dbt-core to use"
        type: string
        required: true
        default: "main"


permissions: read-all

# will cancel previous workflows triggered by the same event and for the same ref for PRs or same SHA otherwise
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref || github.sha }}
  cancel-in-progress: true

jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update Adapters and Core branches
        if: ${{ github.event_name == 'workflow_call' || github.event_name == 'workflow_dispatch'}}
        shell: bash
        run: |
          ./.github/scripts/update_dev_packages.sh \
            ${{ github.event.inputs.core_branch }} \
            ${{ github.event.inputs.dbt_adapters_branch }}

      - name: Setup postgres
        shell: bash
        run: psql -f ./scripts/setup_test_database.sql
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: postgres

      - name: Setup `hatch`
        uses: dbt-labs/dbt-adapters/.github/actions/setup-hatch@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run integration tests
        run: hatch run integration-tests:all
        env:
          POSTGRES_TEST_HOST: localhost
          POSTGRES_TEST_PORT: 5432
          POSTGRES_TEST_USER: root
          POSTGRES_TEST_PASS: password
          POSTGRES_TEST_DATABASE: dbt
          POSTGRES_TEST_THREADS: 4

      - name: Publish results
        uses: dbt-labs/dbt-adapters/.github/actions/publish-results@main
        if: always()
        with:
          source-file: "results.csv"
          file-name: "integration_results"
          python-version: ${{ matrix.python-version }}
