name: Integration Tests

on:
  push:
    branches:
      - "main"
      - "*.latest"
  pull_request:
  workflow_dispatch:

permissions: read-all

env:
  POSTGRES_TEST_HOST: localhost
  POSTGRES_TEST_PORT: 5432
  POSTGRES_TEST_USER: root
  POSTGRES_TEST_PASS: password
  POSTGRES_TEST_DATABASE: dbt
  POSTGRES_TEST_THREADS: 4

# will cancel previous workflows triggered by the same event and for the same ref for PRs or same SHA otherwise
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref || github.sha }}
  cancel-in-progress: true

jobs:
  integration:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup postgres
        uses: ./.github/actions/setup-postgres-linux

      - name: Setup `hatch`
        uses: dbt-labs/dbt-adapters/.github/actions/setup-hatch@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run integration tests
        run: hatch run integration-tests:all

      - name: Publish results
        uses: dbt-labs/dbt-adapters/.github/actions/publish-results@main
        if: always()
        with:
          source-file: "results.csv"
          file-name: "integration_results"
          python-version: ${{ matrix.python-version }}
