name: Integration Tests

on:
  push:
    branches:
      - "main"
      - "*.latest"
  pull_request:
  workflow_dispatch:

permissions: read-all

env:
  DBT_INVOCATION_ENV: github-actions
  DBT_TEST_USER_1: dbt_test_user_1
  DBT_TEST_USER_2: dbt_test_user_2
  DBT_TEST_USER_3: dbt_test_user_3
  POSTGRES_TEST_HOST: localhost
  POSTGRES_TEST_PORT: 5432
  POSTGRES_TEST_USER: root
  POSTGRES_TEST_PASS: password
  POSTGRES_TEST_DATABASE: dbt
  POSTGRES_TEST_THREADS: 4

# will cancel previous workflows triggered by the same event and for the same ref for PRs or same SHA otherwise
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref || github.sha }}
  cancel-in-progress: true

jobs:
  integration:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup `hatch`
        uses: dbt-labs/dbt-adapters/.github/actions/setup-hatch@config/release
        with:
          python-version: ${{ matrix.python-version }}

      - name: Start the postgres service
        run: |
          sudo systemctl start postgresql.service
          pg_isready
        shell: bash

      - name: Configure the database
        run: |
          chmod +x setup_postgres_linux.sh
          sudo -u postgres bash setup_postgres_linux.sh
        shell: bash
        working-directory: ./.github/scripts

      - name: Run integration tests
        run: hatch run integration-tests:all
        shell: bash

      - name: Publish results
        uses: dbt-labs/dbt-adapters/.github/actions/publish-results@config/release
        if: always()
        with:
          source-file: "results.csv"
          file-name: "integration_results"
          python-version: ${{ matrix.python-version }}
