# **what?**
# - respond to user comments by updating issues from `awaiting_response` to `triage`
#
# **why?**
# - automate issue triage
#
# **when?**
# - users comment on issues
name: Issue bot

on:
    issue_comment:

permissions:
    issues: write

jobs:
    triage:
        name: Update triage label
        if: >-
            contains(github.event.issue.labels.*.name, 'awaiting_response') &&
            github.event == 'issue_comment'
        uses: dbt-labs/actions/.github/workflows/swap-labels.yml@main
        with:
            add_label: triage
            remove_label: awaiting_response
        secrets: inherit
