name: Release

on:
  workflow_dispatch:
    inputs:
      deploy-to:
        type: choice
        description: Choose where to publish (test/prod)
        options:
        - prod
        - test
        default: prod
      ref:
        description: "The ref (sha or branch name) to use"
        type: string
        default: "main"
        required: true

permissions: read-all

# will cancel previous workflows triggered by the same event and for the same ref for PRs or same SHA otherwise
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref || github.sha }}-${{ inputs.deploy-to }}
  cancel-in-progress: true

jobs:
  release:
    name: PyPI - ${{ inputs.deploy-to }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.deploy-to }}
      url: ${{ vars.PYPI_PROJECT_URL }}
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: "${{ inputs.ref }}"

      - name: Setup `hatch`
        uses: dbt-labs/dbt-adapters/.github/actions/setup-hatch@main

      - name: Inputs
        id: release-inputs
        run: |
          version=$(hatch version)
          archive_name=dbt-postgres-$version-${{ inputs.deploy-to }}
          echo "archive-name=$archive_name" >> $GITHUB_OUTPUT

      - name: Build `dbt-postgres`
        uses: dbt-labs/dbt-adapters/.github/actions/build-hatch@main
        with:
          archive-name: ${{ steps.release-inputs.outputs.archive-name }}

      - name: Publish to PyPI
        uses: dbt-labs/dbt-adapters/.github/actions/publish-pypi@main
        with:
          pypi-repository-url: ${{ vars.PYPI_REPOSITORY_URL }}
          archive-name: ${{ steps.release-inputs.outputs.archive-name }}
