# What?
#
# Tag and release an arbitrary ref. Uploads to an internal archive for further processing.
#
# How?
#
# After checking out and testing the provided ref, the image is built and uploaded.
#
# When?
#
# Manual trigger.

name: "Release internal patch"

on:
  workflow_dispatch:
      ref:
        description: "The ref (sha or branch name) to use"
        type: string
        default: "main"
        required: true
      package_test_command:
        description: "Package test command"
        type: string
        default: "python -c \"import dbt.adapters.postgres\""
        required: true

defaults:
  run:
    shell: "bash"

jobs:
  invoke-reusable-workflow:
    name: "Build and Release Internally"

    uses: "dbt-labs/dbt-release/.github/workflows/internal-archive-release.yml@addPythonScriptComparison"

    with:
      package_test_command: "${{ inputs.package_test_command }}"
      dbms_name: "postgres"
      ref: "${{ inputs.ref }}"

    secrets: "inherit"
