name: Release

on:
  workflow_dispatch:
    inputs:
      deploy-to:
        type: choice
        description: Choose where to publish (test/prod)
        options:
        - prod
        - test
        default: prod

permissions: read-all

defaults:
  run:
    shell: bash

# will cancel previous workflows triggered by the same event and for the same ref for PRs or same SHA otherwise
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref || github.sha }}-${{ inputs.deploy-to }}
  cancel-in-progress: true

jobs:

  release:
    name: PyPI - ${{ inputs.deploy-to }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.deploy-to }}
      url: ${{ vars.PYPI_PROJECT_URL }}
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup `hatch`
        uses: dbt-labs/dbt-adapters/.github/actions/setup-hatch.yml@main

      - name: Build `dbt-postgres`
        uses: dbt-labs/dbt-adapters/.github/actions/build-hatch.yml@main

      - name: Publish to PyPI
        uses: dbt-labs/dbt-adapters/.github/actions/publish-pypi.yml@main
        with:
          pypi-repository-url: ${{ vars.PYPI_REPOSITORY_URL }}
